### ISSUE TITLE
how about this? (html parser)

### ISSUE THREAD

**Issue by neuromagus** [mickeynp/html-ts-mode#1]
Maybe u know answer on my question...
So, I compiled some grammars (for example, html, css, c etc) and enable in init.el
```
(setq major-mode-remap-alist
      '((js-mode . js-ts-mode)
        (json-mode . json-ts-mode)
        (c-mode . c-ts-mode)
        (csharp-mode . csharp-ts-mode)
        (css-mode . css-ts-mode))
```
all works fine except 'html'. I did not found in list of ts modes any mentions of html-ts-mode...

this is my modes:
![html](https://github.com/mickeynp/html-ts-mode/assets/63796667/4b585ae4-023d-436e-9aa8-7d13f2dedf26)

and this is my compiled grammars in ~/.config/emacs/tree-sitter
![grammars](https://github.com/mickeynp/html-ts-mode/assets/63796667/9054eb5d-7e83-4e82-ace5-aecdd1a0a3f0)

I use precompiled Emacs29.1 or compile from sources (Welcome, Gentoo/Crux ;))
All checkers of TS says - 't' and work fine on another languages.

So, my question is - this is problem of exacly HTML grammar (but people use it (hello, Nvim users)) or problem in TS Emacs?

Do you try enable exacly this grammar? I mean ```(html-mode . ???-ts-mode)```. Or this is behavior in only my config (very clean)?

I live in Russia and lists.gnu.org did not open (need VPN and I have it, but wtf? This is freedom? Well, that's beyond the scope of the question...).

Sorry for my terrible english.

**Comment by mickeynp** [comment]
You need to evaluate the code in the package then use `html-ts-mode` to activate.

**Comment by neuromagus** [comment]
Thanks for your fast response. What do u mean in 'evaluate'? I read documentation and did not found any answers. Maybe u have instruction... I will be very grateful 😊 

Or u mean your code? ```It's a meant to demonstrate``` or this working version?

I found this: https://github.com/emacs-mirror/emacs/blob/master/lisp/textmodes/html-ts-mode.el

**Comment by mickeynp** [comment]
The example major mode works fine, by the way. It's "a demo" because I wrote an article on how to write a major mode with tree sitter. But it works fine -- I use it myself. The alternative you found may also work fine; I have not tried it.

**Comment by neuromagus** [comment]
thanks a lot for answer. 

>It's "a demo" 
>But it works fine

Nice news, put in my config. 
My link is not work on default Emacs29.1 (why need evaluate?), but writen... Well, I think need a time for use community this 'new' way and regex gone.
